### ISSUE TITLE
Site doesn't work properly in Safari

### ISSUE THREAD

**Issue by ezhevita** [cawolfkreo/Cease-and-Desist-History-Big-N#61]
After opening the website no events are displayed, since Safari struggles with parsing JSON file with them:
<img width="1158" alt="Screenshot 2022-11-03 at 18 40 08" src="https://user-images.githubusercontent.com/24438339/199766570-95ac5472-dacc-49b2-a141-ddf416624929.png">

There is the corresponding error message in the developer console:
```
[Error] Unhandled Promise Rejection: RangeError: date value is not finite in DateTimeFormat format()
	format (main.js:241)
	(anonymous function)
	createDataCell (main.js:241)
	map
	updateGrid (main.js:263)
	(anonymous function) (main.js:278)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

The first record that caused this error was this one:
https://github.com/cawolfkreo/Cease-and-Desist-History-Big-N/blob/60b4dff9a84e0d7bdf625231d637d0599c3025fe/data/data.json#L37-L43

Apparently, Safari does not tolerate a single-digit month number and throws an error while trying to parse it.

**Comment by cawolfkreo** [comment]
The simplest solution here, without using some external libary, as you can guess, is updating every date to apply the full "YYYY-MM-DD" format instead of having this mix of dates. I'll do this after work later today, thank you for telling me about this!! 

**Note to anyone in the future who might see this and it's looking for a solution**, Apparently Safari is [a bit of a diva](https://stackoverflow.com/questions/16616950/date-function-returning-invalid-date-in-safari-and-firefox) when it comes to parsing dates and it is important to have the full date in the [ISO8601](https://en.wikipedia.org/wiki/ISO_8601).

**Comment by ezhevita** [comment]
may I contribute and do this myself? I know this ain't much, but it's honest work!

**Comment by cawolfkreo** [comment]
Yes you may!! ~~and I would love you for it~~. Just make a PR of your branch and add me as a reviewer before submitting!
